version: 2.1
jobs:
  build:
    working_directory: ~/poppy
    docker:
      - image: ocaml/opam:ubuntu-20.04-ocaml-4.12
    steps:
      - checkout
      - restore_cache:
          keys:
            - opam-cache-v1-{{ checksum "poppy.opam" }}
      - run:
          name: Install system dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y cmake wget
            wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
            echo "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-14 main" | sudo tee -a /etc/apt/sources.list.d/llvm-toolchain-focal-14.list
            sudo apt-get update
            sudo apt-get install -y llvm-14-dev
      - run:
          name: Install dependencies
          command: |
            eval $(opam env)
            opam update
            opam install . --deps-only --with-test --locked
      - save_cache:
          key: opam-cache-v1-{{ checksum "poppy.opam" }}
          paths:
            - ~/.opam
      - run:
          name: Build and run tests
          command: |
            eval $(opam env)
            dune build @install
            dune runtest
